In [1]:
import numpy as np


In [3]:
m=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(m)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [5]:
m[1,:,1]=[1,2]

In [6]:
print(m)

[[[1 2]
  [3 4]]

 [[5 1]
  [7 2]]]


In [8]:
m[:,1,:].shape


(2, 2)

In [9]:
m[:,1,:]=[[9,9],[8,8]]

In [10]:
print(m)

[[[1 2]
  [9 9]]

 [[5 1]
  [8 8]]]
