In [5]:
import numpy as np


In [9]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [10]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [11]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
np.random.rand(4,2,1)

array([[[0.31856159],
        [0.45892831]],

       [[0.63931379],
        [0.21410814]],

       [[0.61558563],
        [0.10935098]],

       [[0.48257719],
        [0.14642074]]])

In [15]:
m=np.array([[1,2,3],[4,5,6]])


In [17]:
np.full((3,2),7)

array([[7, 7],
       [7, 7],
       [7, 7]])

In [18]:
np.full(m.shape,7)

array([[7, 7, 7],
       [7, 7, 7]])

In [19]:
np.full_like(m,7)

array([[7, 7, 7],
       [7, 7, 7]])

In [21]:
np.random.rand(4,2)

array([[0.49466175, 0.78165139],
       [0.53226431, 0.42861065],
       [0.58953014, 0.52370647],
       [0.61445544, 0.909427  ]])

In [24]:
np.random.random_sample(m.shape)

array([[0.9470378 , 0.91068025, 0.40005453],
       [0.47616811, 0.42093144, 0.09328898]])

In [27]:
np.random.randint(1,10,size=(m.shape))

array([[3, 7, 9],
       [8, 8, 1]])

In [28]:
n=np.array([[1,3,4,5],[6,7,8,9]])


In [29]:
cp=np.repeat(n,4,axis=0)

In [30]:
print(cp)

[[1 3 4 5]
 [1 3 4 5]
 [1 3 4 5]
 [1 3 4 5]
 [6 7 8 9]
 [6 7 8 9]
 [6 7 8 9]
 [6 7 8 9]]


In [31]:
n=np.array([[1,3,4,5,6,7,8,9]])
cp=np.repeat(n,4,axis=0)
print(cp)

[[1 3 4 5 6 7 8 9]
 [1 3 4 5 6 7 8 9]
 [1 3 4 5 6 7 8 9]
 [1 3 4 5 6 7 8 9]]


In [32]:
n=np.array([1,3,4,5,6,7,8,9])
cp=np.repeat(n,4,axis=0)
print(cp)

[1 1 1 1 3 3 3 3 4 4 4 4 5 5 5 5 6 6 6 6 7 7 7 7 8 8 8 8 9 9 9 9]


In [35]:
#question
q=np.ones((5,5))

In [36]:
print(q)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [37]:
q[1:4,1:4]=0
print(q)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [38]:
q[2,2]=9
print(q)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [39]:
#copying
a=np.array([1,2,3])
b=a
b[0]=6
print(a)

[6 2 3]


In [40]:
#therefore to prevent changes in a
a=np.array([1,2,3])
b=a.copy()
b[0]=6
print(a)

[1 2 3]
