In [1]:
import numpy as np


In [2]:
f=np.genfromtxt('test1.txt', delimiter=',',dtype='int32')
print(f)

[[11  2  3  4  5  6  7  8]
 [12  3  4 57  8  6  7  8]
 [ 4  6  2  1 22  1  6  4]]


In [3]:
 f<100

array([[ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True]])

In [4]:
f>50

array([[False, False, False, False, False, False, False, False],
       [False, False, False,  True, False, False, False, False],
       [False, False, False, False, False, False, False, False]])

In [5]:
%time f>10

CPU times: user 17 μs, sys: 0 ns, total: 17 μs
Wall time: 17.9 μs


array([[ True, False, False, False, False, False, False, False],
       [ True, False, False,  True, False, False, False, False],
       [False, False, False, False,  True, False, False, False]])

In [6]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [7]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])