In [3]:
import numpy as np


In [4]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[3,2,4],[6,7,8]])


In [5]:
a+b

array([[ 4,  4,  7],
       [10, 12, 14]])

In [6]:
a*b

array([[ 3,  4, 12],
       [24, 35, 48]])

In [7]:
np.cos(a)

array([[ 0.54030231, -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029]])

##linear algebra


In [9]:
 #matrix multiplictaion
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[3,2,4],[6,7,8],[2,3,4]])
np.matmul(a,b)

array([[21, 25, 32],
       [54, 61, 80]])

In [19]:
#statistics
np.max(a,axis=1)

array([3, 6])