In [1]:
import numpy as np

In [2]:
#change shape
a=np.array([[1,2,3],[4,5,6]])
b=a.reshape((6,1))
print(b)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [4]:
c=np.array([[1,2,3],[2,3,4]])
d=np.array([[4,5,6],[4,3,2]])
np.vstack([c,d])

array([[1, 2, 3],
       [2, 3, 4],
       [4, 5, 6],
       [4, 3, 2]])

In [5]:
np.hstack([c,d])

array([[1, 2, 3, 4, 5, 6],
       [2, 3, 4, 4, 3, 2]])